apiVersion: v1
data:
    CANISTER_DATABASE_URL: ENC[AES256_GCM,data:tCJQqwnvSDHGFpBoiVC8Ko8SyqnmjDzF+f4bp3/pjrNKK+MbDegl94bGvI3gWmETkkuDAQs5qXx3s4AW0o3ze/xQrtZgt2aqB4bO9sXTzEbUCGvl8WLKNcAtXNy8i89QSfaHndSCQggjC1pQ6HYeOg==,iv:hXeBxWG7CW5YpF9/wNaFE+h7JjruOa+Rm3TovvAyMYE=,tag:Hm2pgZ0nuG4ChNOo8E13Sg==,type:str]
    CANISTER_HEARTBEAT_URL: ENC[AES256_GCM,data:mgDadl0ZhrvwB736Ip2fvyB8PcPU/bkNLLpmdbR8gPCZN3FJk1TpHNB/dgBpTZxYChg92B9+G3K6cf01f4ndUeyOb+ZiADrQ00jgef+ee5z1TahLkd3wilu8baFiEW1B,iv:5hS+ICLhFnoKOqbkQh/1dy+Lg3EtjWK/vYlndTZYhy0=,tag:g3ZWeiP91s9acbI0ax7Gpg==,type:str]
    CANISTER_MANIFEST_URL: ENC[AES256_GCM,data:8+9ogEJSrP55s1lhpuseoClo8QszYTSBoi6ypu8P8IF2GnTANN5w6wlu4g+iY/szH9wq3xtCtwUKfREM4yG18TYLqeU=,iv:YtXWFCaqRpUuZGDnhQsdTbMu5Pdrr4zd3KciPD1s7tg=,tag:ovtmx3sjS15u06uqT4x2YQ==,type:str]
    CANISTER_SENTRY_DSN: ENC[AES256_GCM,data:9cPfN1lHqWGrpo3GL5hoHHTTqpOMcnTk3UnoAmGtBdva8P44TbwVphSTznMeRtGpnwJ7ZBz3hyT8JA9yXhz+sLdDzLB/CXBcG0LY/7oD+9mWsv4GP2SUM+aKyPIPxdw3Ph6JlWYmwIDy7E08P2LJGzaEEpw=,iv:rwK0vpwrCMNKjd7bxDnqd6zf3Q0LwneW80UaVatEooc=,tag:lElTP1/w4usCeM0c3vst1A==,type:str]
    CANISTER_TYPESENSE_API_KEY: ENC[AES256_GCM,data:6CA9Qs2DRDQ=,iv:UcLpgHGO0O8rVUTjX+giQr9vzIdwT3vMAjd2VMTkZ0w=,tag:gFqP+xAsA7hA3CAkbz/2jw==,type:str]
    CANISTER_TYPESENSE_ROOT_KEY: ENC[AES256_GCM,data:jXOqKfYwJ4yZYKcJ3gIDlvtVVr4cS4Cg5Ok1gArpmnQp+wQsIzyYZg9iC/vfoU/mjoU/0BQ3lsH4GwSPHouLAab4/zej1q1hxqd0+/idlTTsRcwDIaz6Qw==,iv:rEgzW/4wsMpK39rwx1sumsx7lvQzkLvFE8XcGW9m1Yw=,tag:NOQykXePfm2Zez+vFISTIg==,type:str]
    CANISTER_TYPESENSE_URL: ENC[AES256_GCM,data:I+FE3e0l9jmQFjvaEVVaJbLl9cKWoTt5wcfcdEWRMz0qBiWe0Vrfjw==,iv:u5MJOEceJSR02x81gvDQRVN53kgZ8aN06cPtZgPMl54=,tag:CiRfuzZnLMSOil0U5D1FPg==,type:str]
kind: Secret
metadata:
    name: core-kv
    namespace: canister
type: Opaque
sops:
    age:
        - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMTljMGJJZFV3NUFRUkMz
            VW5zNGJUdDJleHNKQXFpL0V1S0VqRFRkYlVNCkZsM2RJL2hRTCtZZWVtd1dxY3BQ
            MUcvVkxhMnArb21vVVJCT2d0Y1ZYWnMKLS0tIEQxbmZKNVB5eHVUZWtWeERuN29Q
            WWs0OUdPQS9xSFgyUVZDaGN0dk14MWsKvanh+xKIwAx423CD2oF3itvUD8QKYEIE
            9Kl+vxkE224bs7GriWadg/Jn4dbRJPHyrEWiyAI7TheE8pYSSyCHuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T15:16:34Z"
    mac: ENC[AES256_GCM,data:185oTx7db6AHqZTTjN0ZyD6U7LNUm4Mqu6vFSxPs2iig7ksUky/tilsCq9nuwHPfdrTqodMpqLWbmJ8Tvszq8zzJfZ9FnJnXF9na8y2ix2md7fg9Pf/bPWMaj0jWCQmKpSMjaaccNWRc78GPg84pGW6qVVWh84EV013e157S/n8=,iv:ZuHGKY20FqjvQc3PaouK6TNR5FHd668jh/iSKvbTnWc=,tag:msComqV5rR4R55fJchix5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
