apiVersion: v1
data:
    CANISTER_API_ENDPOINT: ENC[AES256_GCM,data:XWga+SR+lyGGMJHfedU5AhhthWi3UmLf4WzopvWLZtVr2x+9,iv:3AsoPcb6NEqHaLSCZH+hbX6mTV9QxGDPpIngf+GUV+0=,tag:YGJu9NPr9nTRegVuwoIZqQ==,type:str]
    CANISTER_DATABASE_URL: ENC[AES256_GCM,data:28lblbnR9v7ALaF1Q7tj+/eJMUG0m621QodfuNx9L3axYaWMvnMUQBFCCEWHiJQ7gjjgXFwHhaqk5rAGHvyAHeFkYJa/mB8BZC8cotOCdNksdBDMXB31ujfHKt2OI9qaccWYmS1zFmLxDR3XtPu6og==,iv:d0NRJK2otYs2FVYxIUQG06lgrv6JX8G9KyRUCFr0Ypo=,tag:2e9Jzh3oNpaHBKxlEgoaRg==,type:str]
    CANISTER_DOCS_ENDPOINT: ENC[AES256_GCM,data:avKQE2qX8XsqmRAGdnsljN0bKn83x3FAuZrxDe7GufY=,iv:sxCIFS6bK69k69gBEomfqNQl97bkwAx8z35uD5N7OKY=,tag:K18gM8vNW12mx2v1vUD5UQ==,type:str]
    CANISTER_META_CODE: ENC[AES256_GCM,data:pmwBVRM5UHw=,iv:9wF70RKIUQSh1ii8Wyn+H92bgKoMBuXmZ4a6JXFmRhQ=,tag:S9zvAjHja0h+iDgvRL2w2g==,type:str]
    CANISTER_META_COPYRIGHT: ENC[AES256_GCM,data:lxLKqQIQYX9LR6pJAMyIONZfrLl9Ne/NV+ss4FGuT3w=,iv:3tEb+0VrexgVZUTnOVZM8VgnVAHgJlyUK1qCZBBOFM4=,tag:O6onxiyxuqMDE6Ho1UAuvg==,type:str]
    CANISTER_META_EMAIL: ENC[AES256_GCM,data:AVcvKa8jvk4cH42rnhlDmeJjlaAYhSJ3j6+T7A==,iv:AtWeMbN++S31XGuWzPDo/zCiJJwWQ6Qxc5s67M2sJKI=,tag:wZC5aiKP8kvfYZgCAu4FUg==,type:str]
    CANISTER_META_NAME: ENC[AES256_GCM,data:dRZlmq4lf/v+H0XO,iv:3MgrhHTHbj4BbOrdF2HnrnNvFykGysi73ILWhHkTweI=,tag:RPv+216SSTNE4Xtw/E+ehA==,type:str]
    CANISTER_OPENAPI_ID: ENC[AES256_GCM,data:NAPqJGGvoFcfCqrSw6hS+NIMv+CuEVQs9EEv3mTz85zhP3/G48ScMOH9NjDha4Qo,iv:faIUHbtwmaDWrrMSJFILLQ1jm2aEObo6pq883+psK74=,tag:1ZxLM9ZWQwM8p03LF3PO7A==,type:str]
    CANISTER_OPENAPI_TOKEN: ENC[AES256_GCM,data:npFzAMfugU3Z3wiIy2zhAHBM7Ohnl7oDxrr1VhXJIpFolJ2YCNKKdho0yu4=,iv:ns4LJixvCEy5Q/C0dUXideSm/RD5JXPctOFp2ivsKM0=,tag:8t71PychccNtYiI4j8Ww3A==,type:str]
    CANISTER_PIRACY_URL: ENC[AES256_GCM,data:adLDVccrH/w90WRCU296yc27vsvc37p9D0496ARiLftTEAqClpEswpk1biBC+Oo7XFAQqKWPs/8LfhsCN9eJ0Cmc37c=,iv:g6/bdTImHBZKBVBpKZ9vtPg4NixH2bKdhG0kgFcod5E=,tag:G5BNxs8jJY+yxfGLdLqheA==,type:str]
    CANISTER_PRIVACY_ENDPOINT: ENC[AES256_GCM,data:NmZf34boMbA5idsJrpJitMOvTgWrKEDW177KUq5ZpWd4SJZJ,iv:kEcT7qf3XQT+O0PRNm1XxiCy4WGVTpvr97YjWrR7e/8=,tag:YJ7P/07MJ92JIOERfr1b8w==,type:str]
    CANISTER_PRIVACY_UPDATED: ENC[AES256_GCM,data:b2xff9f+w6JqMNzuGVV0/g==,iv:bAAG+dP5edbYDrqLDX2/AxmLEVrMRcrNXBYX28dlrHs=,tag:HrQFlkBlQxgKn2xCxQNLRg==,type:str]
    CANISTER_SENTRY_DSN: ENC[AES256_GCM,data:0Z9Obd5zvJjzCa8OdEoWwFkjawvY0USGmyS0UKwcK7Oik1Tx4dXfH5nyeHurB5fnB3m4oKqCECV2A8i2rrUugXQpXLh/cD64jrAFgdlKl22Gx5KSJa04W/zleyYQ8wXcAVDX3gzz9xv9wMJ0ob0aGA==,iv:YJvfguYpRefw6Hnwmf2Noo3SyRa0CwPEFrUwO0C5j7k=,tag:Wv2kB2LUasTZvlXToz10uQ==,type:str]
    CANISTER_TYPESENSE_API_KEY: ENC[AES256_GCM,data:cjVqeX6IqjE=,iv:XC838vbNcklDWM8WMWH9Hsg3Ai1fGcZpg6TUdduk3Sw=,tag:ZY2QKeL4iyfWVGcIeEnLCA==,type:str]
    CANISTER_TYPESENSE_URL: ENC[AES256_GCM,data:1lLMKz5smgDgLw81fyVTm8lXWqfP3fVWCG3gK4xbpU4u9JqRXEe4tQ==,iv:4wqjAKy1TM2B/C653odcyigncEHBR29nIsoM1vaLr5k=,tag:Atu1eHr5ga5oErlPj7+iqA==,type:str]
    CANISTER_VECTOR_URL: ENC[AES256_GCM,data:AKNMbp1ZOtJcU1liND6ZDWkG3JwSV9hW,iv:3Iw6HHWMELAcCdsgJDTe8INFJ/Hoh/OyOPJtWJRK5Sw=,tag:pDojRGhtO+vlayQCBC0f3A==,type:str]
kind: Secret
metadata:
    name: api-kv
    namespace: canister
type: Opaque
sops:
    age:
        - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUlpBbi9Yck91Mk9CaUVs
            d1VyMnF1T2FiRERxWTN2WVd6R0pCQUMzNnowCkZNTlVEY29Jd3NFcWhvZHlIV3d3
            a1A2Z25nbVJTbUhXYmNRcnJrVmtSNlkKLS0tIGR0TVNxWmw4elFPK0JpbkE1bTBO
            aWtBLzF5YXZDQ2cvK2ZKTTZubjVRWjAKYi4uIQfsv2xHVImEPSch4sUQsVnsxQOR
            TWyliRnaMUKzujf0w1KWCTxAPV9HEcFv95nRSgLsAimk54oGdCjnZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T15:16:34Z"
    mac: ENC[AES256_GCM,data:LQxq8JFddHtFVZgsTXSRfO1bYY/+v8G/yDIgO8GJCDP2N2tw86w3hO7G9q4OHtSIJtCWO55t0fNpcr+lcUQRwF8QyW/mEdqo8snMXLea5mI1IryyWY2CShsxMQU48sVsD2yWY5P1rAlrjvmR4hCZjbUePZCstt+FYjmYufVHGXs=,iv:keSfisudbb3D4D/aO+DV6kl8CBkner0E4EvIMIqtQLM=,tag:QCaw3nkl0IMM1dmWRR0sxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
