apiVersion: v1
data:
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:9KvAaZ2xmr5quZw/FaYx538sJPyO2n4UmvyhlbNlcI1KzhQ6zbRt/aZm0NNU/WijrM7SVitcT+kwO/BlQeX7RtXPBQ8Yu2oIpDFNlMo4hmhhADmhJjAP1g==,iv:FegXspYjfViY8T0k/AtvC8Mm+gNKi2y5aIfwKeiGf8U=,tag:WQ2NhsKoZ6zulD6Fj0IDUg==,type:str]
kind: Secret
metadata:
    name: typesense-kv
    namespace: canister
type: Opaque
sops:
    age:
        - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK0lIMXJHM3JzTmlkdGVD
            cW4wd0NweWZ3a2ZiQTlaTFBKZFUxeG9GOFNBClFReS9PNDI1VVRLUDNwVjd1allK
            M3FGSjRidTdKVjA2M05lNTlobkxIRncKLS0tIDluRS92MUZ5M2hJZEJXbmNhbEpt
            eTk5KzJtMWt5UVVZellGb3VIRkNZUzQKllVfYY1w3C3xkDeHQWp+MYvqoLQqokpG
            S5T605jNNzvaPvxRsY5N2YHco144j3gZeXMn7pcqC8SxtpnjPX8yhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T15:16:34Z"
    mac: ENC[AES256_GCM,data:BJwVgGD8iuvf69dJf1uSqKDSoTgH46v+H7jskMMAvbyvxOROr70QnkiM7cBso65klLS9iAAkQNKxFr0cHbyZHe/X+o39xk3ORqD73yIZncPRoNtsFoDcIy3Z+j87VkcgLE4WFcN7Ium1gmSqHGr8xeT0nvj5+vsb/ob/mkA8/IY=,iv:xfwGgJ3a8Pw1qd5oZ7bkp0IGK+Y/iNIrUWK4q2Q0w8M=,tag:hEYDOfME/ETiTCBOFhq2ZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
