apiVersion: v1
data:
    VECTOR_CONFIG: ENC[AES256_GCM,data:SPhifcDI2XPfKlqqHE53sq5uQneqpOhGCIdMdxWLP6lh79Em+I1SAIH0doYqg8BlyjGHkLeoGkskRwI7VgaIJj7zNvNAi9I6tQ7lDYn7bxF9Sc2v2vmSmPQ72D8hjcvEVL661aNm7gYWL4E6d70nBK7nuFIXvIMzxSB9oqvwY86pAi1zrTJreaHaDK57Tv/CrEOkncadNZ8prNFJ3xAhpSc5ulhZOcFrg/CFwbMKjojiqgQnMzJ+tjtf29XQt9BBOcv5nMuoBw87OWcn7Y44iFkKiOP0/oFf924pJN3JpLE0VQZthexNinouzn3VFXpn3in0+snRKkze7yZ2Q8GpgB2sheJgw5N2SkO7/TvTXXbS3UJbCNr/zEXAWHf6VvsmZYLOkv7bPWHGTVP5Ax00ikYRSqrwrJ0toUSlw8FA48O2Bph4sIbZaFBhP160kDvAIM8nvqcCEDgq0rikNDsGNj4DOjiML2CoL3nB6sCFsY/QGER5jr3znM4BTUL0/5DdWZF7aLnapRehrDK6z/wyOM45eBijULmHR0VKdZ1IJQUXQO6FFcFeOTr60w1iCX68DcnMwJqpuAc5wlcY+NVKCTG1v0qsfyc8R5M8PigaqO0sop+Bl5SDw11nAV5rlfa50Ir0fdcJEAUeKFeGShKiKPa4w0XxdDufyy6lWpT2w/1d0FKNWxmIJGy9DP6Ohzzz+KSZ35g40dbeRG6pZaMPfsJSgkA=,iv:vRTtfVfvh1NhHK5dh85TE7dinfCuOEsgbbA+nQ8Fvqg=,tag:o20ZU16jNH8RSHVWlV5JmA==,type:str]
kind: Secret
metadata:
    name: vector-kv
    namespace: canister
type: Opaque
sops:
    age:
        - recipient: age1694wse79axvlhlll9te66wqx0xzqcwu0age2dewtdfv9mu07jfxq0wmlzr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdG90V0duQXBCSWxyaGpY
            ZmxyaDQraEM1YWJhMGd4d0l5QVlkWjNDNTE0CjZVTUtlSVd3eFkzWHdLcy9wV2h6
            eTd1Y25yK0tnVVBJWWFtSU1zWEI1S1kKLS0tIGNmZDlvUXl3RHhZb2VpTUFFSWFL
            TXlNZEd5RE9lazdqVFc0Sm8vLzlBNjQKf+IkTuPKPZ1UXsBX5WP8OOvBJEOGIFEs
            WkH/1zdrAONd9glIGmEAQFnrpqgfdz+vK1zGhm5BnHERD8z29DQy8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T15:16:34Z"
    mac: ENC[AES256_GCM,data:DezKDFnbmRndLB0m0K7KkOILQEKHF+0EtD/Qx665u3QCJXRUeTh8U+21qhye3VMwzzTxUS6x7WUwF7WGaYw1MDNfv/nuWWFX49esKpaSuQ6zFgtNysyytypLbO4ZHFadIRc0DrgOEOM5k7WR8+AStsknrzzF9TCZSUbRVTy2HJM=,iv:gG7+DazKYovl0u/huk3fmVOhK+pWI/45SbtMWZqIRyY=,tag:29CLfeQiP8he9sC18YDWug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
